language: ruby
rvm: 2.6
matrix:
  include:
    # See https://docs.travis-ci.com/user/reference/osx/
    - os: osx
      osx_image: xcode11
      # macOS 10.14
    # - os: osx
    #   osx_image: xcode10
    #   # macOS 10.13
    # - os: osx
    #   osx_image: xcode9
    #   # macOS 10.12
install:
  - brew update
  - brew cask install xquartz
  # - mkdir -p /usr/local/Homebrew/Library/Taps/abcang/homebrew-azpainter
  # - cp -r Formula /usr/local/Homebrew/Library/Taps/abcang/homebrew-azpainter/
script:
  - brew audit --strict ./Formula/azpainter.rb
  - brew install --verbose ./Formula/azpainter.rb
  - open $(brew --prefix azpainter)/AzPainter.app
  - sleep 10
  - pgrep azpainter
  - pkill azpainter
