language: ruby
branches:
  only:
    - master
matrix:
  include:
    # See https://docs.travis-ci.com/user/reference/osx/
    - os: osx
      osx_image: xcode11
      # macOS 10.14
    - os: osx
      osx_image: xcode10
      # macOS 10.13
install:
  - brew update
  - brew cask install xquartz
script:
  - brew install --verbose ./Formula/azpainter.rb
  - open $(brew --prefix azpainter)/AzPainter.app
  - sleep 10
  - pgrep azpainter
  - pkill azpainter
