# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
  schedule:
    - cron: "0 0 1 * *"


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-10.14]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - run: brew update
    - run: brew cask install xquartz

    - run: brew install --verbose ./Formula/azpainter.rb

    - run: open $(brew --prefix azpainter)/AzPainter.app
    - run: sleep 10
    - run: pgrep azpainter
    - run: pkill azpainter
